### ISSUE TITLE
挑指法建议

### ISSUE THREAD

**Issue by chasel** [Zhangyanbo/Refashion_ShenQi_MiPu#3]
挑这个指法的减字，竖画能再拉长吗？你现在的这个挑特别像心字的下面那部分！

**Comment by chasel** [comment]
这是万历年间的一本老琴谱的例子，你可以参考一下！
<img width="643" alt="screen shot 2018-01-23 at 10 51 39" src="https://user-images.githubusercontent.com/1614604/35255730-6cc8566e-002b-11e8-8c32-842a6ac4496f.png">

**Comment by Zhangyanbo** [comment]
谢谢建议。目前这个项目，主要工作是对《神奇秘谱》进行重制。而在《神奇秘谱》中，「挑」指法恰恰是「心」字下面那样的形状。各国琴谱有不同的字体，当然可以理解。但是若只论《神奇秘谱》，左边太长的那种挑反而不合适。
